### ISSUE TITLE
Version java check

### ISSUE THREAD

**Issue by Ygarr** [PixelGuys/Cubyz#56]
installed 18 java, but said "it`s old need 11 at least not 8"

**Comment by IntegratedQuantum** [comment]
You probably installed java 8 in the past and it's set as your default java version somewhere.
If you type `java -version` in a terminal (`cmd.exe`) you will see that it uses java 8 instead of java 18.
This is a common problem on windows and it's a bit annoying to get rid of the java 8 installation.

**Comment by Ygarr** [comment]
Thanks I removed all old javas 8 from windows(in cmd I got java 18 though), but now I have:
java -jar .\Cubyz.jar
Exception in thread "main" java.lang.NoClassDefFoundError: pixelguys/json/Json
        at cubyz.utils.Logger.<clinit>(Logger.java:43)
        at cubyz.client.GameLauncher.main(GameLauncher.java:29)
Caused by: java.lang.ClassNotFoundException: pixelguys.json.Json
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 2 more

**Comment by IntegratedQuantum** [comment]
I recommend to use [the launcher](https://github.com/PixelGuys/Cubyz-Launcher/releases) to run the game.
The `Cubyz.jar` file requires a bunch of libraries and assets and cannot simply be launched with `java -jar`.
The launcher takes care about all of this and stores the libraries and assets in `.cubyz` in your home directory.
